sudo: required

services:
  - docker

before_install:
  - docker image build -t bharatchopra/cicd -f Dockerfile.dev .

script:
  - docker container run bharatchopra/cicd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "cicd"
  env: "Cicd-env"
  bucket_name: "elasticbeanstalk-ap-south-1-388844221725"
  bucket_path: "cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
